---
- id: flake8
  name: flake8 Linting
  entry: flake8
  language: python
  types:
    - python
  additional_dependencies:
    - flake8-bugbear
    - flake8-docstrings
- id: isort
  name: isort Import Sorting
  entry: isort
  language: python
  types:
    - python
  args:
    - --profile
    - black
